### ISSUE TITLE
Move chart

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control-chart#1]
- [ ] Move https://github.com/flanksource/incident-commander/tree/main/chart here, including the publishing workflow to charts.flanksource.io
- [ ] Update canary-checker release workflow to update this chart
- [ ] Update config-db release workflow to update this chart
- [ ] Update incident-commander release workflow to update this chart
- [ ] Update flanksource-ui release workflow to update this chart

**Comment by Joeshiett** [comment]
Hey @moshloop I do not have push and pull access to the repositories: config-db, flanksource-ui, incident-commander.

**Comment by Joeshiett** [comment]
@moshloop I do have some questions. 
- Concerning the chart https://github.com/flanksource/incident-commander/tree/main/chart you want to be moved. Regarding the `release.yml` workflow for the `incident-commander` repo, under the `helm` job, will setting the step that includes a `with:` and `repository`:
```- uses: actions/checkout@v3
        with: 
          repository: "${{ github.repository_owner }}/incident-commander-chart"
```
be ideal for automatically updating the `chart` and `image version`, as well as the `image tags` in the `incident-commander-chart` repo? Or should this be left alone, meaning the `chart version, `image version`, `image tags` will be update in some other way?

-  Also it seems the charts.flanksource.io is currently not accessible.
- Also concerning the workflow for the `incident-commander-chart` will its main function just be to update the chart repo, and push changes to the chart repo?
