### ISSUE TITLE
Kubernetes Agent in MiniKube gets Postgres pvc error storageclass.storage.k8s.io "default" not found

### ISSUE THREAD

**Issue by junaid-ebrahim** [flanksource/mission-control-chart#146]
The Kubernets postgres POD is never started due to the PVC error 

This is caused by the fact that we specify a blank value for {{ .Values.db.storageClass }} in https://github.com/flanksource/mission-control-chart/blob/main/chart/values.yaml. The result of this is that the 'storageClassName' is blank when rendering by helm for https://github.com/flanksource/mission-control-chart/blob/main/chart/templates/postgres.yaml.

A possible fix would be to remove the value {{ .Values.db.storageClass }} in https://github.com/flanksource/mission-control-chart/blob/main/chart/values.yaml
    
Or we can workaround the issue by overriding this value in the helm install of the agent by adding the option below
`--set db.storageClass=standard` This works around the issue by specifying a valid storageClassName for the statefulset.

**Comment by adityathebe** [comment]
https://github.com/flanksource/mission-control-chart/blob/11d0a8f21b8fbe0e73ba691dc8cbcc64bacae8ea/agent-chart/values.yaml#L81
