### ISSUE TITLE
Node memory usage includes evicted pods

### ISSUE THREAD

**Issue by moshloop** [flanksource/mission-control-chart#151]

**Comment by yashmehrotra** [comment]
Currently, prometheus always returns empty result when you query usage for evicted pods
```
container_memory_working_set_bytes{container!="",pod!=""}
  * on(pod, namespace) group_left
kube_pod_status_reason{reason="Evicted"} > 0
```

**Comment by yashmehrotra** [comment]
The problem is that it will give more negatives as we only have pod and namespace but not uid in container_memory query, which would lead to removal of statefulsets if a previous stateteful set is evicted

**Comment by yashmehrotra** [comment]
container_memory_working_set_bytes{container!="",pod!=""}
  * on(pod, namespace) group_left

kube_pod_status_phase{phase="Running"} > 0
