### ISSUE TITLE
Allow disabling incident commander and config-db subcharts

### ISSUE THREAD

**Issue by yashmehrotra** [flanksource/mission-control-chart#20]
@paddatrapper Can you help me track the relevant changes in the karina repo

I'll run the PR by you for review

**Comment by paddatrapper** [comment]
Need to update https://github.com/flanksource/karina/tree/master/manifests/upstream/canary-checker and re-generate https://github.com/flanksource/karina/blob/master/manifests/canary-checker.yaml via `make canary-checker.yaml`

**Comment by moshloop** [comment]
@paddatrapper why did we need this again? Can't we use those subcharts directly ?

**Comment by paddatrapper** [comment]
I think it was an issue with subchart configuration. The config was being duplicated, so the idea was to merge them all and make it all 1 chart. @yashmehrotra am I remembering correctly?
